# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)


2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
# Elementwise subtraction
print(B - C)
# Elementwise multiplication
print(B * C)
# Matrix multiplication
print(B @ C)


[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print("exponentiation = ",np.exp(B))
print("-----------------------------")
print("min. value in the whole matrix = ",np.min(B))
print("-----------------------------")
print("min. value in each row = ", np.min(B, axis=1))
print("-----------------------------")
print("min. value in each column = ", np.min(B, axis=0))
print("-----------------------------")
print("index for min. value in the whole matrix = ", np.argmin(B))
print("-----------------------------")
print("index for min. value in each row = ", np.argmin(B, axis=1))
print("-----------------------------")
print("sum of all elements = ", np.sum(B))
print("-----------------------------")
print("mean for each column = ", np.mean(B, axis=0))
print("-----------------------------")
print("median for each column = ", np.median(B, axis=0))





exponentiation =  [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
-----------------------------
min. value in the whole matrix =  1
-----------------------------
min. value in each row =  [1 4 7]
-----------------------------
min. value in each column =  [1 2 3]
-----------------------------
index for min. value in the whole matrix =  0
-----------------------------
index for min. value in each row =  [0 0 0]
-----------------------------
sum of all elements =  45
-----------------------------
mean for each column =  [4. 5. 6.]
-----------------------------
median for each column =  [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [35]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [36]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Providing fewer indices than axes means that I am slicing along a single axis.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [37]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [40]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [45]:

# np.arange(30) creates a 1D array with values from 0 to 29. 
# b = a.reshape((2, 3, -1)) reshapes the 1D array into a 3D array with 2 blocks each with 3 columns and the remaining axis will be inferred from the other axes.
# then we print the original array a, then we do print() which is an empty line, and then we print the reshaped array b. 

a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [46]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [47]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [49]:
A = np.arange(1, 5).reshape(2,2)
print(A)
print("--------------------------------")
b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
--------------------------------
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [109]:
def add_mult_matrices(m1, m2, add_or_mult):
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray): #validate that the input are of the type numpy.ndarray
        raise ValueError("Input arguments must be of the type numpy.ndarray")
    if add_or_mult not in ['add', 'multiply']: #validate that the third argument is either 'add' or 'multiply'
        raise ValueError("The third argument must be either 'add' or 'multiply'")
    if m1.shape != m2.shape: #validate that the matrices have the same size
        raise ValueError("Matrices must have the same size")
    if add_or_mult == 'add': #if the third argument is 'add'
        return m1 + m2
    else: #if the third argument is 'multiply'
        return m1 @ m2
    

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [113]:
import numpy as np

# Definiera vektorn x
x = np.array([[4], [3]])
print("-------------------------")

# (a) Dimensionen av x
print("(a) Dimensionen:", x.shape)
print("-------------------------")

# (b) Beräkna 5x
print("(b) 5x =", 5 * x)
print("-------------------------")

# (c) Beräkna 3x
print("(c) 3x =", 3 * x)
print("-------------------------")

# (d) Beräkna 5x + 3x
print("(d) 5x + 3x =", 5 * x + 3 * x)
print("-------------------------")

# (e) Beräkna 8x
print("(e) 8x =", 8 * x)
print("-------------------------")

# (f) Beräkna 4x - x
print("(f) 4x - x =", 4 * x - x)
print("-------------------------")

# (g) Transponera x
x_T = x.reshape(-1, 1)
print("(g) Dimensionen av x^T:", x_T.shape)
print("-------------------------")

# (h) Kontrollera om x + x^T är definierat
print("(h) x + x^T =", x + x_T)
print("-------------------------")

# (i) Beräkna ||x||
print("(i) ||x|| =", np.linalg.norm(x))


-------------------------
(a) Dimensionen: (2, 1)
-------------------------
(b) 5x = [[20]
 [15]]
-------------------------
(c) 3x = [[12]
 [ 9]]
-------------------------
(d) 5x + 3x = [[32]
 [24]]
-------------------------
(e) 8x = [[32]
 [24]]
-------------------------
(f) 4x - x = [[12]
 [ 9]]
-------------------------
(g) Dimensionen av x^T: (2, 1)
-------------------------
(h) x + x^T = [[8]
 [6]]
-------------------------
(i) ||x|| = 5.0


In [114]:
import numpy as np

v = np.array([[3], [7], [0], [11]])
print("-------------------------")

# (a) Dimensionen av v
print("(a) Dimensionen:", v.shape)

print("-------------------------")

# (b) Beräkna 2v
print("(b) 2v =", 2 * v)

print("-------------------------")


# (c) Beräkna 5v + 2v
print(" (c) 5v+2v =", 5 * v + 2 * v)

print("-------------------------")


# (d) Beräkna 4v - 2v
print(" (d) 4v - 2v =", 4 * v + 2 * v)

print("-------------------------")

# (e) Beräkna v**T
print(" (e) v transponerat =", v.T)
print("Ny dimension:", v.T.shape)

print("-------------------------")

# (c) Beräkna normen ||v|| 
print("(f) ||v|| =", np.linalg.norm(v)) # vektorns storlek (magnitude)




-------------------------
(a) Dimensionen: (4, 1)
-------------------------
(b) 2v = [[ 6]
 [14]
 [ 0]
 [22]]
-------------------------
 (c) 5v+2v = [[21]
 [49]
 [ 0]
 [77]]
-------------------------
 (d) 4v - 2v = [[18]
 [42]
 [ 0]
 [66]]
-------------------------
 (e) v transponerat = [[ 3  7  0 11]]
Ny dimension: (1, 4)
-------------------------
(f) ||v|| = 13.379088160259652


In [115]:
import numpy as np

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) Beräkna ||v1|| (normen av v1)
print("(a) ||v1|| =", np.linalg.norm(v1))

print("-------------------------")


# (b) Beräkna ||v1 - v2|| (normen av v1 - v2)
print("(b) ||v1 - v2|| =", np.linalg.norm(v1 - v2))

(a) ||v1|| = 7.14142842854285
-------------------------
(b) ||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [116]:
import numpy as np

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

# (a) 2A
print("(a) 2A =", 2 * A)

print("-------------------------")


# (b) B - 2A (multiplicera A med -2 och använd addition, använd min funktion add_mult_matrices)
try:
    print("(b) B - 2A =", add_mult_matrices(B, -2 * A, 'add'))
except ValueError as e:
    print("(b) Error:", f"{e}")

print("-------------------------")


# (c) 3C - 2E 
try:
    print("(c) 3C - 2E =", add_mult_matrices(3 * C, -2 * E, 'add'))
except ValueError as e:
    print("(c) Error:", f"{e}")

print("-------------------------")

# (d) 2D - 3C 
try:
    print("(d) 2D - 3C =", add_mult_matrices(2 * D, -3 * C, 'add'))
except ValueError as e:
    print("(d) Error:", f"{e}")

print("-------------------------")

# (e) D^T + 2D (multiplicera D^T med 2 och använd addition)
try:
    print("(e) D^T + 2D =", add_mult_matrices(D.T, 2 * D, 'add'))
except ValueError as e:
    print("(e) Error:", f"{e}")

print("-------------------------")


# (f) 2C^T - 2D^T (multiplicera D^T med -2 och använd addition)
try:
    print("(f) 2C^T - 2D^T =", add_mult_matrices(2 * C.T, -2 * D.T, 'add'))
except ValueError as e:
    print("(f) Error:", f"{e}")

print("-------------------------")

# (g) A^T - B
try:
    print("(g) A^T - B =", add_mult_matrices(A.T, -1 * B, 'add'))
except ValueError as e:
    print("(g) Error:", f"{e}")

print("-------------------------")

# (h) AC
try:
    print("(g) AC = ", add_mult_matrices(A, C, 'multiply'))
except ValueError as e:
    print("(g) Error:", f"{e}")

print("-------------------------")

# (i) CD
try:
    print("(g) CD = ", add_mult_matrices(C, D, 'multiply'))
except ValueError as e:
    print("(g) Error:", f"{e}")

print("-------------------------")

# (j) CB

try:
    print("(j) CB = ", add_mult_matrices(C, B, 'multiply'))
except ValueError as e:
    print("(j) Error:", f"{e}")

print("-------------------------")

# (k) CI

try:
    print("(k) CI = ", add_mult_matrices(C, I, 'multiply'))
except ValueError as e:
    print("(k) Error:", f"{e}")

print("-------------------------")

# (l) AB^T
try:
    print("(l) AB^T =", add_mult_matrices(A, B.T, 'multiply'))
except ValueError as e:
    print("(l) Error:", f"{e}")

print("-------------------------")


(a) 2A = [[ 4  2 -2]
 [ 2 -2  2]]
-------------------------
(b) B - 2A = [[ 0 -4  3]
 [ 0 -2 -4]]
-------------------------
(c) Error: Matrices must have the same size
-------------------------
(d) 2D - 3C = [[3 2]
 [2 3]]
-------------------------
(e) D^T + 2D = [[ 9 12]
 [12  9]]
-------------------------
(f) 2C^T - 2D^T = [[-4 -4]
 [-4 -4]]
-------------------------
(g) Error: Matrices must have the same size
-------------------------
(g) Error: Matrices must have the same size
-------------------------
(g) CD =  [[11 10]
 [10 11]]
-------------------------
(j) Error: Matrices must have the same size
-------------------------
(k) CI =  [[1 2]
 [2 1]]
-------------------------
(l) Error: Matrices must have the same size
-------------------------


In [117]:
A = np.array([[2, 3, 4], [5, 4, 1]])

# AA^T
try:
    print("AA^T=", add_mult_matrices(A, A.T, "multiply"))
except ValueError as e:
    print("Error", f"{e}")



Error Matrices must have the same size


In [118]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print(A@B)
print("-----------------")
print(A@C)


[[ 4  7]
 [ 8 14]]
-----------------
[[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [120]:
# To check if v1 and v2 is a view or copy, we can use the base attribute. 
# If v1.base is not None, then v1 is a view, otherwise it is a copy.
# view means that a new array is created
# copy means that the same data is simply copied to a new memory location.

v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [121]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [122]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
